language: python
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
script:
- pytest --cov lunch_buddies
- flake8
after_success:
- coveralls
- pip install -r requirements.txt
- pip install zappa
- test $TRAVIS_BRANCH = "master" && zappa update production
- test $TRAVIS_BRANCH = "master" && zappa schedule production
