language: python
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
script:
- pytest --cov lunch_buddies
- flake8
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
