language: python
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
script:
- flake8
after_success:
- coveralls
- pip install -r requirements.txt
- pip install zappa
- zappa update dev
- test $TRAVIS_BRANCH = "master" && zappa update production
